title = "Tring Bellringers"
baseURL = "https://tringbells.org/"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
Paginate = 10
googleAnalytics = "G-DVSMVMTXEQ"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/logo.png"
  site_logo = "images/logo.png"
  description = "Home of the Tring church bell ringers"
  background_color_class = "bg-silver"
  recent_posts_number = 3
  custom_css = ["css/tring-custom.css"]

  email = "info@tringbells.org"


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = '/about/'
    weight = 10

  [[menu.main]]
    identifier = "history"
    name = "History"
    url = '/history/'
    weight = 15

  [[menu.main]]
    identifier = "join_us"
    name = "Join"
    url = '/join-us/'
    weight = 20

  [[menu.main]]
    identifier = "news"
    name = "News"
    url = '/news/'
    weight = 80

  [[menu.main]]
    identifier = "weddings"
    name = "Weddings"
    url = '/weddings/'
    weight = 90

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = '/contact/'
    weight = 100
