title = "Tring Bellringers"
baseURL = "https://tringbells.org/"
languageCode = "en-us"
theme = ["ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
Paginate = 10
googleAnalytics = "G-DVSMVMTXEQ"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/favicon.png"
  site_logo = "images/logo.png"
  description = "Home of the Tring church bell ringers"
  background_color_class = "bg-tring"
  recent_posts_number = 1
  custom_css = ["css/tring-custom.css"]

  email = "info@tringbells.org"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Join"
    url = "/join-us/"
    weight = 20
    [menu.main.params]
      class = "nav-cta"

  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 30

  [[menu.main]]
    name = "History"
    url = "/history/"
    weight = 40

  [[menu.main]]
    name = "Weddings"
    url = "/weddings/"
    weight = 50

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 60
